
const recipe = [ {
    Plat:"Poke Bowl", Ingredient: "650 g de saumon cru (sans la peau et sans arrête), 1 avocat, 1/2 cuilliere à café de gingenbre en poudre, 85g desauce sauja, 20g d'huile de sesame, 2 cuillere à soupe de sucre, graine de sesame grillé, 500g de riz a sushi cru, 5 cuillere  a soupe de vinaigre de riz, 3 cuillere a soupe rases de sucre, 1 cuillere à café de sel", Recette:"1. Cuisez le riz à sushi selon les instruction du paquet. Pendant ce temps, préparez l’assaisonnement du riz en mélangeant le vinaigre de riz, 3 cuillères à soupe de sucre en poudre et le sel. 2. Lorsque le riz est prêt, laissez-le reposer 10 minutes, versez ensuite l’assaisonnement dessus et mélangez délicatement. Laissez tiédir ou refroidir. 2. Coupez le saumon et l’avocat en cubes de 0,5 à 1 cm de côté et placez-les dans un saladier. Préparez la sauce en mélangeant le gingembre, la sauce soja, l’huile de sésame, 2 cuillères à soupe de sucre et le wasabi. 3. Versez cette préparation sur le poisson et mélangez. Réservez au frais jusqu’au moment de servir. Remplissez un bol de riz, couvrez de poisson et avocat et terminez en parsemant de graines de sésame.", Note:"5/5", Image:"poke-bowl.jpg", Temp:"40m", Persone:"5 persone"    
    },
    {
    Plat:"Gateau Chocolat", Ingredient: "133,5g de chocolat pâtissier, 33,5g de farine, 66,5g de sucre, 66,5g de beurre + une noix pour le moule, 2 oeuf", Recette:"1. Préchauffez votre four à 180°C (thermostat 6). Dans une casserole, faites fondre le chocolat et le beurre coupé en morceaux à feu très doux. 2. Dans un saladier, ajoutez le sucre, les oeufs, la farine. Mélangez. 3. Ajoutez le mélange chocolat/beurre. Mélangez bien. 4. Beurrez à l'aide d'une feuille de papier essuie-tout et farinez votre moule puis y versez la pâte à gâteau. 5. Faites cuire au four environ 20 minutes. 6. A la sortie du four le gâteau ne paraît pas assez cuit. C'est normal, laissez-le refroidir puis démoulez- le.", Note:"4,7/5", Image:"fondant.jpg", Temp:"40m", Persone:"4 persone"     
    },
    {     
    Plat:"Purée de patate douce", Ingredient: "1,25 kg Patates douces, 31 cl Crème liquide entière, 6,5 cuil. à soupe Huile d'olive, Beurre(un peu), Fleur de sel, Poivre, ", Recette:"1. Épluchez les patates douces et coupez-les en petits cubes. 2. Faites bouillir de l'eau dans une casserole et mettez-les à cuire durant 10m. 3. Égouttez les patates douces puis passez-les au mixer avec la crème, l'huile d'olive, du sel et du poivre. 4. Servez avec une noisette de beurre.", rating:"4,1/5", Image:"puree.jpg", Temp:"10m", Persone:"5persone"     
    },]
    
    export default recipe